### ISSUE TITLE
how to use test mode?

### ISSUE THREAD

**Issue by toppinghand** [cmavro/TempoQR#3]
Can you tell me the parameter configuration of test mode？

**Comment by cmavro** [comment]
After training the model, it will be saved at (lines 256-259 in *train_qa_model.py*):
``` 
 checkpoint_file_name = 'models/{dataset_name}/qa_models/{model_file}.ckpt'.format(
        dataset_name = args.dataset_name,
        model_file = args.save_to
    )
```
Then, you can evaluate this model by running:
```
python ./train_qa_model.py --model tempoqr --mode eval --load_from ${model_file}
```
which will execute lines 368-388 in *train_qa_model.py*.

**Comment by toppinghand** [comment]
thanks!

**Comment by toppinghand** [comment]
I want to ask again another question, what is the connection between ‘ times = a[6].cuda() ’ and ‘ t1 = a[7].cuda() ，t2 = a[8].cuda()’?

**Comment by cmavro** [comment]
Hi, 
- times = a[6].cuda() are the annotated timestamps of the question (these are obtained in ```qa_datasets.py```, following CronKGQA).
- t1 = a[7].cuda() and t2 = a[8].cuda() are the retrieved timestamps from the KG, which are used in TempoQR with Hard-Supervision (Section 4.3 of the paper). These are obtained in ```hard_supervision_functions.py```.

**Comment by toppinghand** [comment]
Thanks for your answer, I almost got it
