### ISSUE TITLE
How did you get the entity/time embedding?

### ISSUE THREAD

**Issue by KiritoSSR** [cmavro/TempoQR#4]
You mentioned in your paper that you used tkbc's paper method to get entity/time embedding，if I want use your method in other dataset，How can I get the perfect pretrain  entity/time embedding? Is the model which get the best score?

**Comment by cmavro** [comment]
Hi,

We followed [this implementation](https://github.com/apoorvumang/CronKGQA/blob/main/tkbc/train_complex_embedding.ipynb), which is adopted from the original [TKBC method](https://github.com/facebookresearch/tkbc/tree/main/tkbc).

**Comment by KiritoSSR** [comment]
> 你好，
> 
> 我们跟随了[这个现实](https://github.com/apoorvumang/CronKGQA/blob/main/tkbc/train_complex_embedding.ipynb)，它是来自原始的[TKBC 方法](https://github.com/facebookresearch/tkbc/tree/main/tkbc)中采用的。

Thanks!!
